#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

filechanged=$(git diff --cached --numstat ./ | wc -l)

echo "file changed  --> $filechanged"
if [ $filechanged != "0" ]
then
  pnpm commitlint --edit "$1"
else
  exit 0
fi
