#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

filechanged=$(git diff --cached --numstat ./ | wc -l)

echo "filechanged  --> $filechanged"
if [ $filechanged != "0" ]
then
  git add .
  pnpm lint-staged
else
  exit 0
fi
